### ISSUE TITLE
Teensy 3.2 with Audio

### ISSUE THREAD

**Issue by JonasVorwerk** [gallegojm/Arduino-Ftp-Server#7]
Thanks for this great library!

Got it working on a Teensy 3.2 with audio shield. Using the FTP program Transmit to transfer files, works perfectly. 
When including the audio.h library errors appear. 

Any suggestions?

Errors: 
/Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/SD/SD.h:29:7: error: redefinition of 'class File'
 class File : public Stream {
       ^
In file included from /Users/jonasvorwerk/Documents/Arduino/libraries/SdFat/src/FatLib/FatLib.h:27:0,
                 from /Users/jonasvorwerk/Documents/Arduino/libraries/SdFat/src/SdFat.h:33,
                 from /Users/jonasvorwerk/Documents/Arduino/libraries/FatFs/src/FatFs.h:32,
                 from /Users/jonasvorwerk/Documents/Arduino/libraries/FatLib/src/FatLib.h:48,
                 from /Users/jonasvorwerk/Documents/Arduino/libraries/FtpServer/src/FtpServer.h:38,
                 from /Users/jonasvorwerk/Downloads/Arduino-Ftp-Server-master/FtpServer/examples/FtpServerTest/FtpServerTest.ino:26:
/Users/jonasvorwerk/Documents/Arduino/libraries/SdFat/src/FatLib/ArduinoFiles.h:122:7: error: previous definition of 'class File'
 class File : public FatFile, public Stream {
       ^
In file included from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/Audio/play_sd_raw.h:32:0,
                 from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/Audio/Audio.h:124,
                 from /Users/jonasvorwerk/Downloads/Arduino-Ftp-Server-master/FtpServer/examples/FtpServerTest/FtpServerTest.ino:31:
/Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/SD/SD.h:64:3: error: 'SdVolume' does not name a type
   SdVolume volume;
   ^
/Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/SD/SD.h:72:33: error: 'SD_CHIP_SELECT_PIN' was not declared in this scope
   boolean begin(uint8_t csPin = SD_CHIP_SELECT_PIN);
